-- Add durable identity and audit fields for content-link recovery.
ALTER TABLE content_links
    ADD COLUMN IF NOT EXISTS content_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS original_url TEXT;

-- Keep per-link history separate from update_log, which tracks Discord ingestion.
CREATE TABLE IF NOT EXISTS content_link_recovery_items
(
    batch_id            VARCHAR(64),
    content_link_id     BIGINT,
    original_url        TEXT,
    replacement_url     TEXT,
    num_reports_before  INT,
    num_reports_after   INT,
    status              VARCHAR(16) DEFAULT 'pending',
    recovery_method     VARCHAR(32),
    imgur_id            VARCHAR,
    downloaded_size     BIGINT,
    trimmed_size       BIGINT,
    trimmed_sha256     CHAR(64),
    error               TEXT,
    started_at          TIMESTAMP DEFAULT NOW(),
    finished_at         TIMESTAMP
);
